import { motion, AnimatePresence } from 'framer-motion';
import React, { useEffect, useState } from 'react';
import { BsCheckAll } from 'react-icons/bs'

import TemplateModal from '../components/TemplateModal';
import { templateModal } from '../config/animations';


function Home() {

    const [isModalOpen, setIsModalOpen] = useState<boolean>(false)
    
    



    const closeModal = () => {
        setIsModalOpen(false)
       
    }

    const openModal = () => {
        setIsModalOpen(true)
       
    }

    /* ========== Set body overflow-hidden if modalOpen */
    useEffect(() => {
        if(isModalOpen) {
            document.body.style.overflow = "hidden"
        } else {
            document.body.style.overflow = "visible"
        }
    }, [isModalOpen])


    const resumeFeatureList = [
        'Professional out-of-the-box resumes, instantly generated by the most advanced resume builder technology available.',
        'Effortless crafting. Real-time preview & pre-written resume examples. Dozens of HR-approved resume templates.',
        'Land your dream job with the perfect resume employers are looking for!'
    ]

    
  return (
    <div className='px-8'>
        <AnimatePresence>
        {
            isModalOpen ? <TemplateModal  isOpen={isModalOpen} close={closeModal}/> : null
        }
        </AnimatePresence>
        <div id='header'  className='mb-4 mt-8 lg:mt-0 h-auto lg:h-[calc(100vh-4rem)] flex flex-col lg:grid grid-cols-2 w-full'>
            <div className='overflow-hidden order-2 lg:order-first my-8 lg:my-0 select-none flex justify-center'>
                <img src='/assets/avatar.png' alt='' className='h-full'/>
            </div>
            <div className='flex flex-col justify-center'>
                <div>
                    <h1 className='uppercase text-4xl lg:text-5xl font-bold'>Impressive Resumes</h1>
                    <h1 className='uppercase text-4xl lg:text-5xl'>Easy Online Builder</h1>
                    <ul>
                        {
                            resumeFeatureList.map((list, i) => (
                                <li key={i} className='flex gap-2 mt-6'>
                                    <BsCheckAll className='text-green-500 text-2xl'/>
                                    <p>{list}</p>
                                </li>
                            ))
                        }
                    </ul>
                    <button onClick={openModal} className='mt-16 inline-block text-white bg-[#9333EA] py-4 px-8 uppercase font-bold rounded-md'>
                        Create Resume
                    </button>
                   
                </div>
            </div>
        </div>
        


        
    </div>
  )
}

export default Home